// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOASttUtcaMIKDNERWHa1Vl4RFbiv0sjc',
    appId: '1:573370758375:web:99aac49dc4eb1f348b5e42',
    messagingSenderId: '573370758375',
    projectId: 'carwash-7b772',
    authDomain: 'carwash-7b772.firebaseapp.com',
    storageBucket: 'carwash-7b772.firebasestorage.app',
    measurementId: 'G-0YB59267DR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjcdkBWBwcvx7t8mWJm9cJTtLkQ8A6QSA',
    appId: '1:573370758375:android:add21b2eff63ccea8b5e42',
    messagingSenderId: '573370758375',
    projectId: 'carwash-7b772',
    storageBucket: 'carwash-7b772.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDodLA3hQ9oLOhDVOJbxB8r2Vkn0WaaV3M',
    appId: '1:573370758375:ios:df36adaf45e5d21d8b5e42',
    messagingSenderId: '573370758375',
    projectId: 'carwash-7b772',
    storageBucket: 'carwash-7b772.firebasestorage.app',
    iosBundleId: 'com.example.carwash',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDodLA3hQ9oLOhDVOJbxB8r2Vkn0WaaV3M',
    appId: '1:573370758375:ios:df36adaf45e5d21d8b5e42',
    messagingSenderId: '573370758375',
    projectId: 'carwash-7b772',
    storageBucket: 'carwash-7b772.firebasestorage.app',
    iosBundleId: 'com.example.carwash',
  );
}
